import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { AnimatedThemeToggler } from "@/components/magicui/animated-theme-toggler";
import { NavBar } from "./components/navbar";
import Providers from "@/components/providers/providers";

const manrope = Manrope({
  variable: "--font-geist-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Tengku M Zainul A • Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased bg-gray-200 dark:bg-neutral-900`}
      >
        <Providers>
          <NavBar>{children}</NavBar>
          <div className="fixed bottom-4 right-4 z-[9999]">
            <AnimatedThemeToggler className="text-gray-200 bg-neutral-900 dark:text-neutral-900 dark:bg-gray-200 rounded-full p-3" />
          </div>
          {/* Social icons now moved to home-section.tsx */}
        </Providers>
      </body>
    </html>
  );
}
