name: Deploy to Vercel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Langkah ini hanya untuk info dan akan melanjutkan meskipun ada warning
      - name: Run linting (informational)
        run: npm run lint || echo "Linting issues found but continuing deployment"
        continue-on-error: true

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      # Deploy langsung menggunakan Vercel Action resmi
      - name: Deploy to Vercel
        id: deploy-vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: true

      # Fallback jika action gagal, coba dengan CLI
      - name: Deploy with Vercel CLI (fallback)
        if: failure() && steps.deploy-vercel.outcome == 'failure'
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} 
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
